import { Table, MenuItem, Reservation } from './types';

export const INITIAL_TABLES: Table[] = [
  // Courtyard by the fountain (البحرة)
  {
    id: 't-1',
    tableNumber: 1,
    nameAr: 'طاولة البحرة الكبرى 1',
    nameEn: 'Fountain Master Table 1',
    section: 'courtyard',
    sectionAr: 'الصحن الداخلي (البحرة)',
    sectionEn: 'Indoor Courtyard (Fountain)',
    capacity: 6,
    status: 'available',
    position: { x: 30, y: 35 }
  },
  {
    id: 't-2',
    tableNumber: 2,
    nameAr: 'طاولة الياسمين 2',
    nameEn: 'Jasmine Table 2',
    section: 'courtyard',
    sectionAr: 'الصحن الداخلي (البحرة)',
    sectionEn: 'Indoor Courtyard (Fountain)',
    capacity: 4,
    status: 'available',
    position: { x: 50, y: 25 }
  },
  {
    id: 't-3',
    tableNumber: 3,
    nameAr: 'طاولة النافورة 3',
    nameEn: 'Fountain Table 3',
    section: 'courtyard',
    sectionAr: 'الصحن الداخلي (البحرة)',
    sectionEn: 'Indoor Courtyard (Fountain)',
    capacity: 4,
    status: 'reserved',
    position: { x: 70, y: 35 }
  },
  {
    id: 't-4',
    tableNumber: 4,
    nameAr: 'طاولة النارنج 4',
    nameEn: 'Bitter Orange Table 4',
    section: 'courtyard',
    sectionAr: 'الصحن الداخلي (البحرة)',
    sectionEn: 'Indoor Courtyard (Fountain)',
    capacity: 2,
    status: 'available',
    position: { x: 35, y: 65 }
  },
  {
    id: 't-5',
    tableNumber: 5,
    nameAr: 'طاولة الرخام 5',
    nameEn: 'Marble Table 5',
    section: 'courtyard',
    sectionAr: 'الصحن الداخلي (البحرة)',
    sectionEn: 'Indoor Courtyard (Fountain)',
    capacity: 2,
    status: 'occupied',
    position: { x: 65, y: 65 }
  },

  // Balcony (الشرفة الدمشقية)
  {
    id: 't-6',
    tableNumber: 6,
    nameAr: 'إطلالة الشرفة 6',
    nameEn: 'Balcony View 6',
    section: 'balcony',
    sectionAr: 'الشرفة الدمشقية',
    sectionEn: 'Damascene Balcony',
    capacity: 2,
    status: 'available',
    position: { x: 15, y: 20 }
  },
  {
    id: 't-7',
    tableNumber: 7,
    nameAr: 'إطلالة الشرفة 7',
    nameEn: 'Balcony View 7',
    section: 'balcony',
    sectionAr: 'الشرفة الدمشقية',
    sectionEn: 'Damascene Balcony',
    capacity: 4,
    status: 'available',
    position: { x: 15, y: 50 }
  },
  {
    id: 't-8',
    tableNumber: 8,
    nameAr: 'طاولة القشلة 8',
    nameEn: 'Al-Qashla Balcony 8',
    section: 'balcony',
    sectionAr: 'الشرفة الدمشقية',
    sectionEn: 'Damascene Balcony',
    capacity: 4,
    status: 'reserved',
    position: { x: 15, y: 80 }
  },

  // VIP Family Section (الجناح الملكي والعائلي)
  {
    id: 't-9',
    tableNumber: 9,
    nameAr: 'جناح باب توما VIP 9',
    nameEn: 'Bab Touma VIP Suite 9',
    section: 'vip',
    sectionAr: 'الجناح الملكي (VIP)',
    sectionEn: 'Royal VIP Suite',
    capacity: 8,
    status: 'available',
    position: { x: 85, y: 20 }
  },
  {
    id: 't-10',
    tableNumber: 10,
    nameAr: 'جناح قصر العظم VIP 10',
    nameEn: 'Azem Palace VIP 10',
    section: 'vip',
    sectionAr: 'الجناح الملكي (VIP)',
    sectionEn: 'Royal VIP Suite',
    capacity: 10,
    status: 'available',
    position: { x: 85, y: 50 }
  },
  {
    id: 't-11',
    tableNumber: 11,
    nameAr: 'ديوان قاسيون VIP 11',
    nameEn: 'Qasioun Lounge VIP 11',
    section: 'vip',
    sectionAr: 'الجناح الملكي (VIP)',
    sectionEn: 'Royal VIP Suite',
    capacity: 8,
    status: 'available',
    position: { x: 85, y: 80 }
  },
  {
    id: 't-12',
    tableNumber: 12,
    nameAr: 'طاولة الياسمين 12',
    nameEn: 'Jasmine Royal 12',
    section: 'vip',
    sectionAr: 'الجناح الملكي (VIP)',
    sectionEn: 'Royal VIP Suite',
    capacity: 6,
    status: 'available',
    position: { x: 50, y: 85 }
  }
];

export const MENU_ITEMS: MenuItem[] = [
  // 1. المقبلات الشامية (Cold & Hot Mezze)
  {
    id: 'm-1',
    categoryId: 'mezze',
    nameAr: 'يلنجي دمشقي فاخر',
    nameEn: 'Luxury Damascene Yalanji',
    descriptionAr: 'ورق عنب محشو بأرز بسمتي، طماطم، بقدونس، وزيت زيتون معصور على البارد ونكهة دبس الرمان.',
    descriptionEn: 'Grape leaves stuffed with rice, tomatoes, parsley, cold-pressed olive oil, and pomegranate molasses.',
    price: 18,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 0,
    isVegetarian: true,
    isChefSpecial: true,
    ingredientsAr: ['ورق عنب', 'أرز', 'طماطم', 'بقدونس', 'دبس الرمان', 'زيت زيتون بكر'],
    ingredientsEn: ['Grape leaves', 'Rice', 'Tomatoes', 'Parsley', 'Pomegranate molasses', 'Extra virgin olive oil'],
    calories: 280
  },
  {
    id: 'm-2',
    categoryId: 'mezze',
    nameAr: 'متبل باذنجان مشوي بالرمان',
    nameEn: 'Smoked Mutabbal with Pomegranate',
    descriptionAr: 'باذنجان مشوي على الحطب مع الطحينية النقية، اللبن، الثوم ورشات الرمان وقطرات الزيت الصافي.',
    descriptionEn: 'Charcoal-roasted eggplant blended with tahini, garlic, yogurt, fresh pomegranate seeds & olive oil.',
    price: 16,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1577906096429-f73c2c312435?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 0,
    isVegetarian: true,
    ingredientsAr: ['باذنجان مشوي', 'طحينة', 'لبن', 'ثوم', 'رمان', 'زيت زيتون'],
    ingredientsEn: ['Smoked eggplant', 'Tahini', 'Yogurt', 'Garlic', 'Pomegranate', 'Olive oil'],
    calories: 220
  },
  {
    id: 'm-3',
    categoryId: 'mezze',
    nameAr: 'حمص باللحمة والصنوبر الذهبي',
    nameEn: 'Hummus Bil Lahme & Golden Pine Nuts',
    descriptionAr: 'حمص شام ناعم يعلوه لحم غنم بلدي محمر بالسمن الحيواني والصنوبر المحمص.',
    descriptionEn: 'Silky chickpea purée topped with sautéed local spiced lamb and toasted golden pine nuts.',
    price: 22,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1637806930600-37fa8893f09d?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 1,
    isChefSpecial: true,
    ingredientsAr: ['حمص', 'لحم غنم بلدي', 'صنوبر محمص', 'سمن بلدي', 'طحينة'],
    ingredientsEn: ['Chickpeas', 'Minced lamb', 'Toasted pine nuts', 'Ghee', 'Tahini'],
    calories: 450
  },
  {
    id: 'm-4',
    categoryId: 'mezze',
    nameAr: 'محمرة بالجوز ودبس الرمان',
    nameEn: 'Walnut Muhammara & Pomegranate',
    descriptionAr: 'مزيج الفلفل الأحمر المشوي بالجوز المفروم، الكعك المطحون، ودبس الرمان الدمشقي.',
    descriptionEn: 'Roasted red pepper dip blended with walnuts, breadcrumbs, and rich pomegranate molasses.',
    price: 15,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 2,
    isVegetarian: true,
    ingredientsAr: ['فلفل أحمر مشوي', 'جوز', 'دبس الرمان', 'كعك مطحون', 'زيت زيتون'],
    ingredientsEn: ['Roasted red pepper', 'Walnuts', 'Pomegranate molasses', 'Breadcrumbs', 'Olive oil'],
    calories: 310
  },

  // 2. المشاوي والفخارات (Grills & Fekharat)
  {
    id: 'g-1',
    categoryId: 'grills',
    nameAr: 'مشاوي مشكلة بيتنا الشامي',
    nameEn: 'Baitna Al-Shami Mixed Grill',
    descriptionAr: 'تشكيلة فاخرة من كباب الحلبي، شيش طاووق التتبيلة الشامية، وقطع ريش الغنم المشوية.',
    descriptionEn: 'Sizzling platter of Aleppo kebab, marinated Shami chicken skewers, and succulent lamb chops.',
    price: 48,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 1,
    isChefSpecial: true,
    ingredientsAr: ['لحم غنم', 'شيش طاووق', 'ريش غنم', 'بصل مشوي', 'طماطم', 'خبز بالبيواز'],
    ingredientsEn: ['Lamb kebab', 'Chicken skewers', 'Lamb chops', 'Grilled onions', 'Tomatoes', 'Biwaz bread'],
    calories: 850
  },
  {
    id: 'g-2',
    categoryId: 'grills',
    nameAr: 'كباب بالكرز الشامي',
    nameEn: 'Cherry Kebab (Kebab Bi Al-Karaz)',
    descriptionAr: 'كباب لحم الغنم الطازج المطبوخ في صلصة الكرز وشربات التوت الشامي الحامض الحلو.',
    descriptionEn: 'Tender grilled lamb kebabs simmered in a sweet and sour wild sour-cherry glaze.',
    price: 36,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 1,
    isChefSpecial: true,
    ingredientsAr: ['كباب لحم', 'صلصة الكرز حامض حلو', 'صنوبر', 'خبز محمص'],
    ingredientsEn: ['Minced lamb kebabs', 'Sour cherry reduction', 'Pine nuts', 'Toasted pita bread'],
    calories: 680
  },
  {
    id: 'g-3',
    categoryId: 'grills',
    nameAr: 'فخارة لحم بالخضار والبهار الشامي',
    nameEn: 'Clay Pot Lamb & Garden Vegetables',
    descriptionAr: 'قطع لحم موزات الغنم مع البطاطا، الباذنجان والبصل المخبوزة بطين الفخار تحت عجين الفرن.',
    descriptionEn: 'Slow-cooked lamb shank with seasonal vegetables sealed in clay pot and freshly baked dough.',
    price: 38,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1547496592-1b9d4be94132?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 1,
    ingredientsAr: ['موزات لحم غنم', 'خضار مشكلة', 'بهارات شامية', 'غطاء عجين'],
    ingredientsEn: ['Lamb shank', 'Mixed vegetables', 'Damascene spices', 'Dough crust'],
    calories: 720
  },

  // 3. الفتات والكبب (Fatteh & Kibbeh)
  {
    id: 'fk-1',
    categoryId: 'fatteh_kibbeh',
    nameAr: 'فتة مقدوس دمشقية',
    nameEn: 'Damascene Fatteh Makdous',
    descriptionAr: 'قطع الباذنجان الصغير المحشو باللحمة، الخبز المحمص، صلصة اللبن مع الطحينة والثوم والفرقعة.',
    descriptionEn: 'Mini stuffed eggplants served over crispy pita, garlic-tahini yogurt, and sizzling ghee with pine nuts.',
    price: 28,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 0,
    isChefSpecial: true,
    ingredientsAr: ['باذنجان محشو باللحم', 'خبز مقرمش', 'لبن وطحينة', 'سمن بلدي وصنوبر'],
    ingredientsEn: ['Meat-stuffed eggplant', 'Crispy pita', 'Garlic tahini yogurt', 'Ghee & pine nuts'],
    calories: 590
  },
  {
    id: 'fk-2',
    categoryId: 'fatteh_kibbeh',
    nameAr: 'كبة صاجية بحشوة الشحم والجوز',
    nameEn: 'Kibbeh Sajieh with Walnuts',
    descriptionAr: 'قرص كبة مشوي على الصاج محشو باللحمة المفرومة، الشحم البلدي، الجوز ودبس الرمان.',
    descriptionEn: 'Traditional griddled Kibbeh discs filled with spiced minced meat, walnuts, and pomegranate molasses.',
    price: 26,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 2,
    ingredientsAr: ['برغل ناعم', 'لحم هبرة', 'جوز', 'شحم بلدي', 'دبس الرمان'],
    ingredientsEn: ['Bulgur wheat', 'Lean lamb', 'Walnuts', 'Spiced fat', 'Pomegranate molasses'],
    calories: 610
  },
  {
    id: 'fk-3',
    categoryId: 'fatteh_kibbeh',
    nameAr: 'كبة مبرومة بالفستق الحلبي',
    nameEn: 'Rolled Pistachio Kibbeh (Mabroumeh)',
    descriptionAr: 'أقراص الكبة المبرومة الذهبية المحشوة بغزارة بالفستق الحلبي الفاخر واللحم البلدي.',
    descriptionEn: 'Golden rolled kibbeh stuffed with generous premium Syrian pistachios and spiced meat.',
    price: 30,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 1,
    isChefSpecial: true,
    ingredientsAr: ['برغل ولحم', 'فستق حلبي فاخر', 'سمن بلدي', 'بهارات دمشقية'],
    ingredientsEn: ['Bulgur & minced meat', 'Aleppo pistachios', 'Ghee', 'Syrian spices'],
    calories: 640
  },

  // 4. الحلويات والمشروبات (Desserts & Drinks)
  {
    id: 'd-1',
    categoryId: 'desserts_drinks',
    nameAr: 'حلاوة الجبن بالآيس كريم الفستق',
    nameEn: 'Halawet El Jibn with Pistachio Cream',
    descriptionAr: 'شرائح عجينة الجبن العكاوي المعطرة بماء الزهر، المحشوة بالقشطة البلدية والفستق الحلبي.',
    descriptionEn: 'Sweet cheese rolls infused with orange blossom, filled with clotted cream & crushed pistachios.',
    price: 18,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 0,
    isVegetarian: true,
    isChefSpecial: true,
    ingredientsAr: ['جبن عكاوي', 'قشطة بلدية', 'ماء زهر', 'قطر معطر', 'فستق حلبي'],
    ingredientsEn: ['Sweet cheese', 'Clotted cream (Ashta)', 'Orange blossom', 'Syrup', 'Pistachios'],
    calories: 410
  },
  {
    id: 'd-2',
    categoryId: 'desserts_drinks',
    nameAr: 'بقلاوة مشكلة بالسمن البلدي',
    nameEn: 'Royal Damascene Baklava Selection',
    descriptionAr: 'رقائق الرقاق المقرمشة بالسمن البلدي المحشوة بأجود أنواع الفستق الحلبي والجوز.',
    descriptionEn: 'Assortment of crispy phyllo pastries layered with Syrian ghee and premium pistachios.',
    price: 20,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 0,
    isVegetarian: true,
    ingredientsAr: ['عجين رقاق', 'فستق حلبي', 'سمن بلدي', 'قطر'],
    ingredientsEn: ['Phyllo dough', 'Pistachios', 'Ghee', 'Sugar syrup'],
    calories: 480
  },
  {
    id: 'd-3',
    categoryId: 'desserts_drinks',
    nameAr: 'شراب التمر هندي والورد الدمشقي',
    nameEn: 'Damascene Tamarind & Rose Water',
    descriptionAr: 'شراب التمر هندي المنعش المحضر يدوياً والمعطر بقطرات ماء الورد الدمشقي الأصيل.',
    descriptionEn: 'Handcrafted refreshing iced tamarind juice infused with authentic Damascene rose water.',
    price: 8,
    currency: '$',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop',
    spiceLevel: 0,
    isVegetarian: true,
    ingredientsAr: ['تمر هندي طبيعي', 'ماء ورد دمشقي', 'ثلج مجروش', 'سكر نقي'],
    ingredientsEn: ['Natural tamarind', 'Damascene rose water', 'Crushed ice', 'Pure sugar'],
    calories: 140
  }
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-101',
    bookingRef: 'BS-8921',
    guestName: 'محمد أحمد العطار',
    guestPhone: '+963 944 123 456',
    guestEmail: 'm.attar@example.com',
    date: new Date().toISOString().split('T')[0],
    timeSlot: '20:00',
    guestsCount: 4,
    tableId: 't-3',
    tableNumber: 3,
    sectionAr: 'الصحن الداخلي (البحرة)',
    sectionEn: 'Indoor Courtyard (Fountain)',
    specialRequests: 'طاولة بقرب النافورة للاحتفال بذكرى زواج.',
    status: 'confirmed',
    createdAt: new Date().toISOString()
  },
  {
    id: 'res-102',
    bookingRef: 'BS-8922',
    guestName: 'سارة الكيلاني',
    guestPhone: '+963 933 987 654',
    guestEmail: 'sara.k@example.com',
    date: new Date().toISOString().split('T')[0],
    timeSlot: '21:00',
    guestsCount: 4,
    tableId: 't-8',
    tableNumber: 8,
    sectionAr: 'الشرفة الدمشقية',
    sectionEn: 'Damascene Balcony',
    specialRequests: 'جلسة هادئة على الشرفة.',
    status: 'confirmed',
    createdAt: new Date().toISOString()
  }
];
